version: '3'

services:
  kafka-sharp-worker:
    image: kafka-isr
#    build:
#      context: .
#      dockerfile: Dockerfile.kafka.cpu
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
      KAFKA_GROUP_ID: ist-kafka-consumer
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_AUTO_COMMIT: 0
      KAFKA_POLLING_TIMEOUT_SECONDS: 30
      MODEL_NAME: noise-cancel
      MODEL_BY_PATCH_OF_SIZE: 30
      MODEL_BATCH_SIZE: 13
      MODEL_PADDING_SIZE: 5
      KAFKA_TOPICS: "user-image-uploaded"
    depends_on:
      - broker