apiVersion: "jimdo.com/v1"
kind: WonderlandService
metadata:
  name: ${PROJECT_NAME}
  labels:
    scope: wonderland-test
spec:
  scale: 2
  components:
    - name: ${PROJECT_NAME}
      image: ${IMAGE}:${TAG}
      capacity:
        memory: XL
        cpu: XXXL
      env:
        HOST_MODE: CPU
        PORT: "8000"
  http-endpoints:
    - component: ${PROJECT_NAME}
      container-port: 8000
      public-domains:
        - ${COMPONENT_NAME}.jimdo-platform-eks.net
        - ${COMPONENT_NAME}.jimdo-platform.net
  notifications:
    slack: "#sharp-bots"